config/routes.rb
Rails.application.routes.draw do
  resources :valid_plates
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :plate do
        get :validate
    end

    resources :pp do
        delete :delete_all, on: :collection
    end

    resources :pos do
        get :filter, on: :collection
        delete :delete_all, on: :collection
    end

    resource :map

    resource :command do
        get :get
        get :image
        post :view
        get :scan
    end
end

app/models/valid_plate.rb
class ValidPlate < ApplicationRecord

    has_one :valid_plate

    def self.match?(number)
        where('light_plate like ?', "%#{number}%").first
    end

end

app/controllers/valid_plates_controller.rb
class ValidPlatesController < ApplicationController
  before_action :set_valid_plate, only: [:show, :edit, :update, :destroy]

  # GET /valid_plates
  # GET /valid_plates.json
  def index
    @valid_plates = ValidPlate.all
  end

  # GET /valid_plates/1
  # GET /valid_plates/1.json
  def show
  end

  # GET /valid_plates/new
  def new
    @valid_plate = ValidPlate.new
  end

  # GET /valid_plates/1/edit
  def edit
  end

  # POST /valid_plates
  # POST /valid_plates.json
  def create
    @valid_plate = ValidPlate.new(valid_plate_params.permit(:owner, :number))
    @valid_plate.light_plate = @valid_plate.number.gsub('-', '')
    respond_to do |format|
      if @valid_plate.save
        format.html { redirect_to @valid_plate, notice: 'Valid plate was successfully created.' }
        format.json { render :show, status: :created, location: @valid_plate }
      else
        format.html { render :new }
        format.json { render json: @valid_plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /valid_plates/1
  # PATCH/PUT /valid_plates/1.json
  def update
    respond_to do |format|
      if @valid_plate.update(valid_plate_params.permit(:owner, :number))
        format.html { redirect_to @valid_plate, notice: 'Valid plate was successfully updated.' }
        format.json { render :show, status: :ok, location: @valid_plate }
      else
        format.html { render :edit }
        format.json { render json: @valid_plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valid_plates/1
  # DELETE /valid_plates/1.json
  def destroy
    @valid_plate.destroy
    respond_to do |format|
      format.html { redirect_to valid_plates_url, notice: 'Valid plate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valid_plate
      @valid_plate = ValidPlate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def valid_plate_params
      params.fetch(:valid_plate, {})
    end
end

app/helpers/valid_plates_helper.rb
module ValidPlatesHelper
end

app/views/valid_plates/_form.html.haml
.form-horizontal
    = form_with(model: valid_plate, local: true) do |form|
        - if valid_plate.errors.any?
            #error_explanation
                %h2
                    = pluralize(valid_plate.errors.count, "error")
                    prohibited this valid_plate from being saved:
                %ul
                    - valid_plate.errors.full_messages.each do |message|
                        %li= message
        .form-group
            %label Number
            = form.text_field :number
        .form-group
            %label Owner
            = form.text_field :owner
        .actions
            = form.submit

app/views/valid_plates/edit.html.haml
%h1 Editing Valid Plate
= render 'form', valid_plate: @valid_plate
= link_to 'Show', @valid_plate
|
\#{link_to 'Back', valid_plates_path}

app/views/valid_plates/index.html.haml
%p#notice= notice
%h1 Valid Plates
%table.table.table-striped.table-hover.table-condensed
    %tr
        %th Number
        %th Owner
        %th Searched
        %th Actions
    - @valid_plates.each do |valid_plate|
        %tr
            %td= valid_plate.number
            %td= valid_plate.owner
            %td= valid_plate.light_plate
            %td
                = link_to 'Edit', edit_valid_plate_path(valid_plate)
                |
                = link_to 'Destroy', valid_plate, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Valid Plate', new_valid_plate_path

app/views/valid_plates/new.html.haml
%h1 New Valid Plate
= render 'form', valid_plate: @valid_plate
= link_to 'Back', valid_plates_path

app/views/valid_plates/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_valid_plate_path(@valid_plate)
|
=link_to 'Back', valid_plates_path