config/routes.rb
Rails.application.routes.draw do
  resources :valid_plates
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :plate do
        get :validate
    end

    resources :pp do
        delete :delete_all, on: :collection
    end

    resources :pos do
        get :filter, on: :collection
        delete :delete_all, on: :collection
    end

    resource :map

    resource :command do
        get :get
        get :image
        post :view
        get :scan
    end
end

app/controllers/pos_controller.rb
class PosController < ApplicationController

    def create
        pos = Position.new(params.permit(:longitude, :latitude, :speed, :scan))
        pos.moment = DateTime.now
        pos.save!
        render plain: 'OK'
    end

    def filter
        @positions = Position.all
        @positions = @positions.with_name(params[:start_time]) if params[:start_time].present?
        @positions = @positions.from_company(params[:end_time]) if params[:end_time].present?
        render partial: 'user_list'
    end

end

app/helpers/pos_helper.rb
module PosHelper
end

app/views/pos/_pos_table.html.haml
%table.table.table-striped.table-bordered.table-hover.table-condensed
    %tr
        %th Time
        %th Longitude
        %th Latitude
        %th Speed (m/s)
    - for pos in Position.all
        %tr
            %td= pos.moment
            %td= pos.longitude
            %td= pos.latitude
            %td= pos.speed

app/views/pos/index.html.haml
.panel.panel-default
    .panel-heading List of positions
    / .panel-body.filter
    /     Start date/time
    /     = text_field_tag :start_time, DateTime.now, id: 'start-time'
    /     End date/time
    /     = text_field_tag :end_time, DateTime.now, id: 'end-time'
    #pos-table= render partial: 'pos_table'

%button.button= link_to 'Delete Table', delete_all_pp_index_path, method: :delete, 